-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALE.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALE.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM USER_INFO INFO, ONLINE_SALE SALE
WHERE INFO.USER_ID = SALE.USER_ID AND GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALE.SALES_DATE), EXTRACT(MONTH FROM SALE.SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER