-- 코드를 입력하세요
SELECT *
FROM (SELECT C.CAR_ID, C.CAR_TYPE, (DAILY_FEE * 30 * (100- DISCOUNT_RATE) / 100) FEE
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE C.CAR_TYPE = P.CAR_TYPE
        AND DURATION_TYPE = '30일 이상'
        AND C.CAR_TYPE IN ('세단', 'SUV'))
WHERE CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD') AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD'))
    AND FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;