-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT OUTS.ANIMAL_ID, OUTS.NAME, OUTS.DATETIME - INS.DATETIME AS DIF
    FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
    WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
    ORDER BY OUTS.DATETIME - INS.DATETIME DESC
)
WHERE ROWNUM <= 2