-- 코드를 입력하세요
SELECT '/home/grep/src/' || B.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
FROM USED_GOODS_BOARD B, (SELECT *
    FROM (SELECT VIEWS
        FROM USED_GOODS_BOARD
        ORDER BY VIEWS DESC)
    WHERE ROWNUM = 1) CV, USED_GOODS_FILE F
WHERE B.VIEWS = CV.VIEWS AND B.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC;