-- 코드를 입력하세요
-- 0시부터 23시까지 전체 시간대에 해당 데이터를 넣어야함
SELECT HOURS.HOUR, COUNT(ANIMAL.TIME) AS COUNT
FROM (SELECT LEVEL-1 HOUR FROM DUAL CONNECT BY LEVEL < 25) HOURS, -- 0~23시 시간대
    (SELECT TO_CHAR(DATETIME, 'HH24') TIME FROM ANIMAL_OUTS) ANIMAL
WHERE ANIMAL.TIME(+) = HOURS.HOUR -- 데이터 없는 시간대도 포함되게
GROUP BY HOURS.HOUR
ORDER BY HOURS.HOUR;