-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP, REST_REVIEW RR, (SELECT MEMBER_ID
    FROM (SELECT MEMBER_ID, COUNT(REVIEW_ID) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT DESC)
    WHERE ROWNUM = 1) TR
WHERE MP.MEMBER_ID = TR.MEMBER_ID AND RR.MEMBER_ID = TR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;