-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BA
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = BA.BOOK_ID AND TO_CHAR(BA.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;