-- 코드를 입력하세요
-- SELECT PRODUCT_CODE, (PRICE * SALES_AMOUNT) AS SALES
-- FROM PRODUCT LEFT JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID

SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) * PRICE AS SALES
FROM PRODUCT, OFFLINE_SALE
WHERE PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE, PRICE
ORDER BY SALES DESC, PRODUCT_CODE